// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBR3ek1Kl07296VILz6VDGQEx2LuK2RtY',
    appId: '1:498359023979:web:7c1ebf3012b8533ee3342e',
    messagingSenderId: '498359023979',
    projectId: 'kairo-status-hub',
    authDomain: 'kairo-status-hub.firebaseapp.com',
    storageBucket: 'kairo-status-hub.firebasestorage.app',
    measurementId: 'G-F6KTFJGXF2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe5kaIw_w1_q-W8zprDn80wz-raTFCS2M',
    appId: '1:498359023979:android:dd000d8ccad0638ae3342e',
    messagingSenderId: '498359023979',
    projectId: 'kairo-status-hub',
    storageBucket: 'kairo-status-hub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwC9zanIXH78vy7xw4JVREG31hzm-GmUE',
    appId: '1:498359023979:ios:eca8836e8c07547ae3342e',
    messagingSenderId: '498359023979',
    projectId: 'kairo-status-hub',
    storageBucket: 'kairo-status-hub.firebasestorage.app',
    androidClientId:
        '498359023979-h6o5ae1cm1i5sfigi9t2bu71g4puu422.apps.googleusercontent.com',
    iosClientId:
        '498359023979-2g092hiu9fq5rf6tt764m6ihkbse3rkc.apps.googleusercontent.com',
    iosBundleId: 'com.example.kairo',
  );
}
